<<<<<<< HEAD
title: Minimal theme
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
=======
>>>>>>> a76d2bb6506cbe17e8a39a9a62436f3bd0d39ff9
theme: jekyll-theme-minimal